version: '3.8'

# Production override for docker-compose.yml
# Use with: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up

services:
  backend:
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - SPRING_JPA_SHOW_SQL=false
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=WARN
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    healthcheck:
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s

  db:
    environment:
      - MYSQL_INNODB_BUFFER_POOL_SIZE=512M
    volumes:
      - db_prod_data:/var/lib/mysql
      - ./docker/mysql/logs:/var/log/mysql
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.25'

volumes:
  db_prod_data:
    driver: local
