version: '3.8'

networks:
  itinerarly-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: itinerarly-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-prod}
      db-url: jdbc:mysql://mysql:3306/${MYSQL_DATABASE:-itinerarly}?useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC&autoReconnect=true
      db-username: ${MYSQL_USER}
      db-password: ${MYSQL_PASSWORD}
      JWT-Secret: ${JWT-Secret}
      FRONTEND_URL: ${FRONTEND_URL}
      github-client-id: ${github-client-id}
      github-secret: ${github-secret}
      google-client-id: ${google-client-id}
      google-secret: ${google-secret}
      APP_DAILY_TOKEN_LIMIT: ${APP_DAILY_TOKEN_LIMIT:-6}
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - itinerarly-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  mysql:
    image: mysql:8.0
    container_name: itinerarly-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-itinerarly}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - itinerarly-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
