version: '3.8'

services:
  backend:
    image: itinerarly-backend:latest
    container_name: itinerarly-backend-prod
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      db-url: ${db-url}
      db-username: ${db-username}
      db-password: ${db-password}
      JWT-Secret: ${JWT-Secret}
      FRONTEND_URL: ${FRONTEND_URL}
      github-client-id: ${github-client-id}
      github-secret: ${github-secret}
      google-client-id: ${google-client-id}
      google-secret: ${google-secret}
      APP_DAILY_TOKEN_LIMIT: ${APP_DAILY_TOKEN_LIMIT:-6}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO:-validate}
      SPRING_JPA_SHOW_SQL: ${SPRING_JPA_SHOW_SQL:-false}
    networks:
      - itinerarly-prod-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

networks:
  itinerarly-prod-network:
    driver: bridge
